export const Strings = {
  APP_TITLE: "Listou",
  HISTORY_TITLE: "Histórico de Compras",
  TABS_HOME_TITLE: "Listou",

  BTN_BACK_TO_LIST: "Voltar para Lista",
  BTN_REUSE_LIST: "Reutilizar Lista",
  
  DRAWER_CURRENT_LIST: "Lista de compras",
  DRAWER_HISTORY: "Histórico",
  
  BTN_ADD_ITEM: "Adicionar Item",
  BTN_SAVE_LIST: "Salvar Lista",
  BTN_DELETE_LIST: "Deletar Lista",
  BTN_CLEAR_LIST: "Limpar Lista",
  BTN_TOGGLE_CHARTS: "Ver Gráficos",
  BTN_HIDE_CHARTS: "Ocultar Gráficos",
  BTN_CLEAR: "Limpar",
  
  MSG_EMPTY_LIST: "Sua lista está vazia",
  MSG_LOADING: "Carregando...",
  MSG_ERROR: "Ocorreu um erro",
  MSG_SAVED: "Lista salva com sucesso!",
  MSG_DELETED: "Lista deletada com sucesso!",
  MSG_DELETE_CONFIRMATION: "Tem certeza que deseja limpar esta lista?",
  MSG_ITEM_ALREADY_EXISTS: "Já existe um item com esse nome na lista.",
  MSG_KEEP_MISSING_ITEMS: "Isso irá manter apenas os itens marcados como faltantes na lista. Deseja continuar?",
  MSG_FILL_WEIGHT_PRICE: "Preencha o valor por kg e o peso",
  
  CHART_ITEMS_BY_CATEGORY: "Itens por Categoria",
  CHART_SPENDING_BY_CATEGORY: "Gastos por Categoria",
  CHART_PRODUCTS_BY_VALUE: "Produtos por Valor",
  
  INPUT_ITEM_NAME: "Nome do Item",
  INPUT_ITEM_PRICE: "Preço",
  INPUT_ITEM_CATEGORY: "Categoria",
  INPUT_ITEM_WEIGHT: "Peso (kg)",
  INPUT_PRICE_PER_KG: "Valor por kg (R$)",
  INPUT_UNIT_PRICE: "Preço unitário",
  INPUT_FILTER_PLACEHOLDER: "Filtrar itens...",
  
  STATUS_GOT: "Obtido",
  STATUS_MISSING: "Faltando",
  
  CONFIRM_DELETE_LIST: "Tem certeza que deseja deletar esta lista?",
  CONFIRM_YES: "Sim",
  CONFIRM_NO: "Não",
  CONFIRM_CANCEL: "Cancelar",
  CONFIRM_DELETE: "Deletar",
  CONFIRM_OK: "OK",
  CONFIRM_CONFIRM: "Confirmar",
  
  ALERT_ERROR: "Erro",
  ALERT_SUCCESS: "Sucesso",
  ALERT_DELETE_LIST: "Deletar Lista",
  ALERT_LIST_COMPLETED: "Lista Concluída!",
  ALERT_LIST_SAVED: "Lista Salva!",
  ALERT_LIST_REUSED: "Lista Reutilizada",
  ALERT_KEEP_MISSING: "Manter apenas itens que faltam",
  
  MSG_ERROR_LOAD_LIST: "Erro ao carregar lista",
  MSG_ERROR_SAVE_LIST: "Erro ao salvar lista",
  MSG_ERROR_DELETE_LIST: "Erro ao deletar lista",
  MSG_ERROR_LOAD_HISTORY: "Erro ao carregar histórico",
  MSG_ERROR_SAVE_HISTORY: "Erro ao salvar lista no histórico",
  MSG_ERROR_REUSE_LIST: "Erro ao reutilizar lista",
  MSG_FILL_PRICE_QUANTITY: "Preencha preço e quantidade",
  MSG_INVALID_VALUES: "Valores inválidos",
  MSG_TYPE_ITEM_NAME: "Digite o nome do item",
  MSG_LIST_MOVED_HISTORY: "A lista foi movida para o histórico.",
  MSG_LIST_COMPLETED: "Todos os itens foram comprados. A lista foi movida para o histórico.",
  MSG_LIST_DELETED: "Lista deletada com sucesso!",
  MSG_LIST_REUSED: "Os itens foram adicionados à sua lista atual",
  MSG_NO_ITEM_SELECTED: "Item não selecionado para confirmação.",
  
  TITLE_ADD_ITEM: "Adicionar Item",
  TITLE_ITEM_NAME: "Nome do Item",
  TITLE_PRODUCT_CATEGORY: "Categoria do Produto",
  TITLE_QUANTITY: "Quantidade",
  TITLE_TOTAL_SPENT: "Total gasto",
  TITLE_KEEP_MISSING: "Manter apenas itens que faltam",
  TITLE_TOP_5_EXPENSIVE: "Top 5 produtos mais caros",
  TITLE_ITEMS_DISTRIBUTION: "Distribuição de Itens",
  TITLE_ADD_FIRST_ITEM: "Adicione o primeiro item na lista",
  TITLE_FIXED_PRICE: "Preço fixo",
  TITLE_PRICE_PER_KG: "Preço por kg",
  TITLE_WEIGHTED_PRODUCT: "Produto vendido por peso",
  TITLE_TOTAL: "Total",
  
  TITLE_SAVE_LIST: "Salvar Lista de Compras",
  TITLE_LIST_NAME: "Nome da Lista",
  PLACEHOLDER_LIST_NAME: "Ex: Compras do Mês",
  MSG_TYPE_LIST_NAME: "Digite um nome para a lista",

  BTN_DELETE_ALL_HISTORY: "Apagar Todo Histórico",
  BTN_DELETE_LIST_HISTORY: "Apagar Lista",
  ALERT_DELETE_HISTORY: "Apagar Histórico",
  ALERT_DELETE_LIST_HISTORY: "Apagar Lista do Histórico",
  CONFIRM_DELETE_ALL_HISTORY: "Tem certeza que deseja apagar todo o histórico? Essa ação não pode ser desfeita.",
  CONFIRM_DELETE_LIST_HISTORY: "Tem certeza que deseja apagar esta lista do histórico? Essa ação não pode ser desfeita.",
  MSG_HISTORY_DELETED: "Histórico apagado com sucesso!",
  MSG_LIST_DELETED_HISTORY: "Lista apagada do histórico com sucesso!",
  MSG_ERROR_DELETE_HISTORY: "Erro ao apagar histórico",

  BTN_SHARE_WHATSAPP: "WhatsApp",
  MSG_ERROR_SHARE_WHATSAPP: "Não foi possível abrir o WhatsApp. Verifique se o aplicativo está instalado.",
  MSG_ERROR_SHARE: "Ocorreu um erro ao tentar compartilhar a lista.",
  WHATSAPP_LIST_TITLE: "📝 Listou - Minha Lista de Compras",
  WHATSAPP_TOTAL_TITLE: "💰 Total"
}
