import { Theme } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const createStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
    paddingHorizontal: 15
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 10,
  },
  deleteButton: {
    backgroundColor: theme.danger,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 6,
    gap: 2,
  },
  deleteButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  historyButton: {
    backgroundColor: theme.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 6,
    gap: 2,
  },
  historyButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  headerButtons: {
    marginBottom: 15,
  },
  saveButton: {
    backgroundColor: theme.success,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 6,
    gap: 2,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  missingListButton: {
    backgroundColor: theme.primary,
    padding: 15,
    borderRadius: 8,
    marginBottom: 20,
    alignItems: "center",
  },
  missingListButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
    color: theme.text.primary,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
    flexWrap: "wrap",
  },
  input: {
    flex: 2,
    minWidth: 120,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 5,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 12,
    backgroundColor: theme.background,
    color: theme.text.primary,
  },
  pickerContainer: {
    flex: 1,
    minWidth: 90,
  },
  buttonContainer: {
    flexBasis: "100%",
    marginTop: 8,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: theme.border,
    marginHorizontal: 4,
  },
  itemQuantity: {
    fontSize: 16,
    marginRight: 8,
    fontWeight: "bold",
    color: theme.text.secondary,
    minWidth: 35,
  },
  itemName: { 
    flex: 1, 
    fontSize: 16, 
    textTransform: "capitalize",
    color: theme.text.primary
  },
  itemGot: {
    textDecorationLine: "line-through",
    color: theme.success,
    fontWeight: "bold",
  },
  itemMissing: {
    color: "#f44336",
    fontWeight: "bold",
    textDecorationLine: "line-through",
  },
  buttonsRow: {
    flexDirection: "row",
    gap: 4,
  },
  actionButton: {
    padding: 8,
  },
  btnText: {
    fontWeight: "bold",
    color: "#333",
  },
  total: {
    fontSize: 20,
    fontWeight: "bold",
    color: theme.text.primary,
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    paddingHorizontal: 30,
  },
  modalContent: {
    backgroundColor: theme.modal,
    borderRadius: 10,
    padding: 20,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 15,
    backgroundColor: theme.background,
    color: theme.text.primary,
  },
  quantityInput: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 15,
    backgroundColor: theme.background,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '500',
    width: '100%',
  },
  itemNameInput: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 15,
    backgroundColor: theme.background,
    color: theme.text.primary,
    fontSize: 18,
    width: '100%',
    textTransform: 'capitalize',
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  categoryTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: theme.text.primary,
    paddingBottom: 8,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  categoryGroup: {
    marginBottom: 16,
    backgroundColor: theme.surface,
    borderRadius: 8,
    padding: 12,
    elevation: 2,
    shadowColor: theme.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.shadow.opacity,
    shadowRadius: 3.84,
  },
  itemPriceQuantity: {
    fontSize: 14,
    color: theme.text.secondary,
    marginLeft: 8,
    marginRight: 8,
  },
  chartTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 20,
    textAlign: "center",
    color: theme.text.primary,
  },
  chartsButton: {
    backgroundColor: theme.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 15,
    borderRadius: 8,
    marginVertical: 15,
    gap: 8,
  },
  chartsButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  chartsContainer: {
    backgroundColor: theme.card,
    borderRadius: 8,
    padding: 15,
    marginTop: 10,
    marginHorizontal: -15,
    elevation: 2,
    shadowColor: theme.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.shadow.opacity,
    shadowRadius: 3.84,
  },
  totalContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: theme.card,
    borderRadius: 10,
    marginTop: 8,
  },
  addButton: {
    position: "absolute",
    right: 20,
    bottom: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    zIndex: 1000,
    shadowColor: theme.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: theme.shadow.opacity,
    shadowRadius: 3.84,
  },
  addButtonCentered: {
    position: "relative",
    width: "auto",
    height: "auto",
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 28,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    marginBottom: 16,
    flexDirection: "row",
    gap: 8,
    alignSelf: "center",
  },
  addButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  emptyStateContainer: {
    flex: 1,
    minHeight: 400,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    width: "100%",
  },
  emptyStateText: {
    fontSize: 16,
    color: theme.text.secondary,
    textAlign: "center",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: theme.text.primary,
  },
  closeButton: {
    padding: 5,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: theme.text.primary,
    marginBottom: 8,
  },
  statisticsList: {
    marginTop: 10,
  },
  statisticsItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.surface,
    marginBottom: 8,
    borderRadius: 8,
    overflow: "hidden",
  },
  statisticsRank: {
    width: 40,
    height: 40,
    backgroundColor: theme.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  statisticsRankText: {
    color: theme.text.inverse,
    fontSize: 16,
    fontWeight: "bold",
  },
  statisticsContent: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statisticsTitle: {
    fontSize: 16,
    color: theme.text.primary,
    marginBottom: 2,
  },
  statisticsValue: {
    fontSize: 14,
    color: theme.text.secondary,
  },
});

export const createHistoryStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  itemQuantity: {
    fontSize: 14,
    color: theme.text.secondary,
    fontWeight: 'bold',
    minWidth: 35,
    marginRight: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    backgroundColor: theme.background,
  },
  deleteAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  deleteAllButtonText: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '500',
  },
  deleteListButton: {
    padding: 4,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 4,
  },
  backButtonText: {
    marginLeft: 8,
    fontSize: 16,
    color: theme.primary,
    fontWeight: '500',
  },
  content: {
    padding: 20,
  },
  listCard: {
    backgroundColor: theme.surface,
    borderRadius: 8,
    marginBottom: 10,
    overflow: 'hidden',
  },
  listHeader: {
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.surface,
  },
  listContent: {
    backgroundColor: theme.card,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    padding: 15,
  },
  listTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.text.primary,
    marginBottom: 4,
  },
  listDate: {
    fontSize: 14,
    color: theme.text.secondary,
  },
  listInfo: {
    fontSize: 14,
    color: theme.text.secondary,
    marginTop: 4,
  },
  listTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.primary,
  },
  placeholder: {
    textAlign: 'center',
    fontSize: 16,
    color: theme.text.secondary,
    marginTop: 20,
  },
  categoryContainer: {
    marginBottom: 15,
  },
  categoryTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.text.primary,
    marginBottom: 8,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  itemName: {
    fontSize: 14,
    color: theme.text.primary,
    flex: 1,
  },
  itemPrice: {
    fontSize: 14,
    color: theme.text.secondary,
    marginLeft: 8,
  },
  reuseButton: {
    backgroundColor: theme.success,
    padding: 12,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
  },
  reuseButtonText: {
    color: theme.text.inverse,
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 8,
  },
});
